- name: Download Discord
  get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb

- name: Remove previous versions of Discord
  become: true
  apt:
    name: discord
    state: absent

- name: Install Discord .deb package
  become: true
  apt:
    deb: /tmp/discord.deb
