- name: Remove neovim
  become: true
  shell: rm -rf ~/src/nvim

- name: Validating if should configure personal
  stat:
    path: "~/.src/nvim/README.md"
  register: nvim_readme_file_status

- name: Update nvim git tags
  shell: "cd ~/.src/nvim && git fetch --tags --force && cd ~/"
  when: nvim_readme_file_status.stat.exists

- name: Clone nvim repository
  git:
    repo: https://github.com/neovim/neovim
    dest: "{{ ansible_env.HOME }}/.src/nvim"
    clone: true
    version: "v0.10.3"

- name: Install nvim build dependencies
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
    state: present

- name: Build neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.src/nvim && make -j 20"

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.src/nvim && make install"

- name: Symlink neovim configurations
  shell: "bash {{ lookup('env', 'HOME') }}/.core/scripts/symlink-create .config/nvim"

- name: Ensure the nvim directory exists
  ansible.builtin.file:
    path: /home/mike/.local/share/nvim
    state: directory
    mode: '0755'

- name: Unzip languageserver into appropriate directory
  unarchive:
    src: /home/mike/.ansible-workstation/files/languageserver
    dest: /home/mike/.local/share/nvim
    remote_src: yes
