- name: Download PGP security keys
  become_method: sudo
  become: true
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
    force_basic_auth: yes

- name: Register PGP security keys
  become: yes
  command: 
    cmd: dpkg -i /tmp/packages-microsoft-prod.deb

- name: Update package lists
  become: true
  apt:
    update_cache: yes 

- name: Install latest version of PowerShell 7
  become: true
  apt:
    name: powershell
