- name: Install package "tmux"
  become: true
  apt:
    name: "tmux"

- name: Symlink .tmux.conf
  shell: "bash {{ lookup('env', 'HOME') }}/.core/scripts/symlink-create .tmux.conf"

- name: Symlink tmux-sessionizer and tmux-nster
  shell: "bash {{ lookup('env', 'HOME') }}/.core/scripts/symlink-create .local/bin/tmux"
